### ISSUE TITLE
import issue: Windows x64 ModuleNotFoundError: No module named '_libvips'

### ISSUE THREAD

**Issue by yuqiyuqitan** [yuqiyuqitan/SPACEc#53]
Error: 
```
import spacec
INFO:root: * TissUUmaps version: 3.1.1.6
Traceback (most recent call last):
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\pyvips\__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\spacec\__init__.py", line 30, in <module>
    from . import tools as tl
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\spacec\tools\__init__.py", line 1, in <module>
    from ._general import (
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\spacec\tools\_general.py", line 65, in <module>
    import tissuumaps.jupyter as tj
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\tissuumaps\__init__.py", line 101, in <module>
    from . import views
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\tissuumaps\views.py", line 24, in <module>
    import pyvips
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\pyvips\__init__.py", line 57, in <module>
    vips_lib = ffi.dlopen('libvips-42.dll')
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips-42.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips-42.dll'
>>> import pyvips
Traceback (most recent call last):
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\pyvips\__init__.py", line 19, in <module>
    import _libvips
ModuleNotFoundError: No module named '_libvips'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\pyvips\__init__.py", line 57, in <module>
    vips_lib = ffi.dlopen('libvips-42.dll')
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\cffi\api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\cffi\api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "C:\Users\Max\anaconda3\envs\spacec_beta\lib\site-packages\cffi\api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library 'libvips-42.dll': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libvips-42.dll
```

**Comment by yuqiyuqitan** [comment]
**Solution**
1: [Download vips-8.6.3-1 64-bit windows binary,](https://github.com/libvips/build-win64-mxe/releases/tag/v8.15.2) unzip to c:\vips-dev-8.6 (can be anywhere)
2: Add the new vips path to your PATH typing this in the powershell: `$env:Path = 'c:\vips-dev-8.6;' + $env:Path`  
or Open "Advanced System Settings" and use the Environment Variables button to add c:\vips-dev-8.6\bin to Path.

This should work.

relevant links:
https://stackoverflow.com/questions/714877/setting-windows-powershell-environment-variables
https://github.com/libvips/pyvips/issues/44
